[package]
name = "spl-token-group-example"
version = "0.2.1"
description = "Solana Program Library Token Group Example"
documentation = "https://docs.rs/spl-token-group-example"
authors = { workspace = true }
repository = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
solana-program = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps-test" }
solana-program-error = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps-test" }
solana-system-interface = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps-test" }
spl-pod = { git = "https://github.com/jupnet/libraries", branch = "fix/sdk-deps-test" }
spl-token-2022 = { git = "https://github.com/jupnet/token-2022", branch = "fix/sdk-deps-test", features = ["no-entrypoint"] }
spl-token-group-interface = { path = "../interface" }
spl-type-length-value = { git = "https://github.com/jupnet/libraries", branch = "fix/sdk-deps-test" }

[dev-dependencies]
solana-program-test = { git = "https://github.com/jupnet/jupnet-svm", branch = "fix/sdk-deps-test" }
solana-sdk = { git = "https://github.com/jupnet/jupnet-sdk", branch = "fix/sdk-deps-test" }
spl-discriminator = { git = "https://github.com/jupnet/libraries", branch = "fix/sdk-deps-test" }
spl-token-client = { git = "https://github.com/jupnet/token", branch = "fix/sdk-deps-test" }
spl-token-metadata-interface = { git = "https://github.com/jupnet/token-metadata", branch = "fix/sdk-deps-test" }

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
